#analysis data obtained from move simulations

bar0_data0a = readRDS("bar0_data0a.RData")
bar0_data0b = readRDS("bar0_data0b.RData")
bar0_data1 = readRDS("bar0_data1.RData")
bar0_data2 = readRDS("bar0_data2.RData")
bar0_data3 = readRDS("bar0_data3.RData")
bar0_data4 = readRDS("bar0_data4.RData")
bar0_data5 = readRDS("bar0_data5.RData")
bar0_data6 = readRDS("bar0_data6.RData")
bar0_data7 = readRDS("bar0_data7.RData")
bar0_data8 = readRDS("bar0_data8.RData")
bar0_data9 = readRDS("bar0_data9.RData")
bar0_data10 = readRDS("bar0_data10.RData")

barA_data0a = readRDS("barA_data0a.RData")
barA_data0b = readRDS("barA_data0b.RData")
barA_data1 = readRDS("barA_data1.RData")
barA_data2 = readRDS("barA_data2.RData")
barA_data3 = readRDS("barA_data3.RData")
barA_data4 = readRDS("barA_data4.RData")
barA_data5 = readRDS("barA_data5.RData")
barA_data6 = readRDS("barA_data6.RData")
barA_data7 = readRDS("barA_data7.RData")
barA_data8 = readRDS("barA_data8.RData")
barA_data9 = readRDS("barA_data9.RData")
barA_data10 = readRDS("barA_data10.RData")

barB_data0a = readRDS("barB_data0a.RData")
barB_data0b = readRDS("barB_data0b.RData")
barB_data1 = readRDS("barB_data1.RData")
barB_data2 = readRDS("barB_data2.RData")
barB_data3 = readRDS("barB_data3.RData")
barB_data4 = readRDS("barB_data4.RData")
barB_data5 = readRDS("barB_data5.RData")
barB_data6 = readRDS("barB_data6.RData")
barB_data7 = readRDS("barB_data7.RData")
barB_data8 = readRDS("barB_data8.RData")
barB_data9 = readRDS("barB_data9.RData")
barB_data10 = readRDS("barB_data10.RData")

x = c(1:2500)
y.low = .6
y.high = 1.5

par(mfrow=c(3,3))
plot(x, bar0_data0a$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data0a$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data0a$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data0a$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data0a$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data0a$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data0a$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data0a$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data0a$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data1$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data2$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data2$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data2$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data2$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data2$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data2$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data2$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data2$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data2$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

y.low = 16
y.high = 33
par(mfrow=c(3,3))
plot(x, bar0_data3$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data3$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data3$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data3$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data3$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data3$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data3$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data3$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data3$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data4$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data4$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data4$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data4$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data4$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data4$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data4$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data4$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data4$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data5$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data5$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data5$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data5$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data5$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data5$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data5$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data5$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data5$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data6$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data6$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data6$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data6$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data6$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data6$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data6$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data6$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data6$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data7$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data7$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data7$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data7$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data7$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data7$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data7$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data7$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data7$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data8$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data8$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data8$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data8$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data8$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data8$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data8$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data8$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data8$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data9$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data9$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data9$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data9$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data9$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data9$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data9$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data9$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data9$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data10$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))


fit.1 = lm(bar0_data0a$MSE[1]$`current_result$MSE[, 1]`~x)
plot(x, bar0_data1$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
abline(lm(bar0_data0a$MSE[1]$`current_result$MSE[, 1]`~(x)^2) ,col="red",lwd=2)
lines(lowess(x,bar0_data0a$MSE[1]$`current_result$MSE[, 1]`), col="blue",lwd=2)
lines(smooth.spline(x,bar0_data0a$MSE[1]$`current_result$MSE[, 1]`), col="green", lwd=2)
smoothed25 <- predict(loess(bar0_data0a$MSE[1]$`current_result$MSE[, 1]`~x , data=bar0_data0a, span=0.25)) 
lines(smoothed25, x=x, col="orange", lwd=3)

#----------------------------BAR A--------------------------------#
x = c(1:2500)
y.low = .6
y.high = 1.5

#Data 0a
par(mfrow=c(3,3))
plot(x, barA_data0a$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data0a$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data0a$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data0a$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data0a$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data0a$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data0a$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data0a$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data0a$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 1
par(mfrow=c(3,3))
plot(x, barA_data1$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 2
par(mfrow=c(3,3))
plot(x, barA_data2$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data2$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data2$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data2$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data2$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data2$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data2$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data2$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data2$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

y.low = 16
y.high = 33
#Data 3
par(mfrow=c(3,3))
plot(x, barA_data3$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data3$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data3$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data3$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data3$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data3$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data3$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data3$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data3$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 4
par(mfrow=c(3,3))
plot(x, barA_data4$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data4$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data4$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data4$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data4$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data4$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data4$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data4$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data4$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 5
par(mfrow=c(3,3))
plot(x, barA_data5$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data5$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data5$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data5$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data5$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data5$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data5$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data5$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data5$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 6
par(mfrow=c(3,3))
plot(x, barA_data6$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data6$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data6$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data6$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data6$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data6$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data6$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data6$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data6$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 7
par(mfrow=c(3,3))
plot(x, barA_data7$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data7$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data7$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data7$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data7$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data7$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data7$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data7$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data7$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 8
par(mfrow=c(3,3))
plot(x, barA_data8$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data8$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data8$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data8$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data8$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data8$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data8$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data8$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data8$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 9
par(mfrow=c(3,3))
plot(x, barA_data9$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data9$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data9$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data9$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data9$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data9$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data9$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data9$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data9$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 10
par(mfrow=c(3,3))
plot(x, barA_data10$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#-------------------------------------BAR B ---------------------------------#
x = c(1:2500)
y.low = .6
y.high = 1.5

#Data 0a
par(mfrow=c(3,3))
plot(x, barB_data0a$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data0a$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data0a$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data0a$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data0a$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data0a$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data0a$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data0a$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data0a$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 1
par(mfrow=c(3,3))
plot(x, barB_data1$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 2
par(mfrow=c(3,3))
plot(x, barB_data2$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data2$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data2$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data2$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data2$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data2$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data2$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data2$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data2$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 3
par(mfrow=c(3,3))
plot(x, barB_data3$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data3$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data3$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data3$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data3$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data3$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data3$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data3$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data3$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 4
par(mfrow=c(3,3))
plot(x, barB_data4$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data4$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data4$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data4$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data4$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data4$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data4$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data4$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data4$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 5
par(mfrow=c(3,3))
plot(x, barB_data5$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data5$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data5$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data5$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data5$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data5$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data5$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data5$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data5$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 6
par(mfrow=c(3,3))
plot(x, barB_data6$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data6$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data6$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data6$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data6$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data6$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data6$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data6$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data6$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#Data 7
y.low = 0
y.high = 2
par(mfrow=c(3,3))
plot(x, barB_data7$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data7$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data7$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data7$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data7$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data7$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data7$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data7$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data7$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

y.low = 0
y.high = 3
#Data 8
par(mfrow=c(3,3))
plot(x, barB_data8$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data8$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data8$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data8$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data8$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data8$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data8$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data8$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data8$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

y.low = 5
y.high = 20
#Data 9
par(mfrow=c(3,3))
plot(x, barB_data9$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data9$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data9$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data9$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data9$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data9$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data9$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data9$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data9$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

y.low = 3
y.high = 17
#Data 10
par(mfrow=c(3,3))
plot(x, barB_data10$MSE[[1]], main = 1, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$MSE[[2]], main = 2, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$MSE[[3]], main = 3, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$MSE[[4]], main = 4, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$MSE[[5]], main = 5, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$MSE[[6]], main = 6, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$MSE[[7]], main = 7, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$MSE[[8]], main = 8, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$MSE[[9]], main = 9, ylab="MSE", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))



#-----------------------------------------BIC---------------------------------#
y.low = 200
y.high = 370
#bar0 Data 1
par(mfrow=c(3,3))
plot(x, bar0_data1$BIC[[1]], main = 1, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$BIC[[2]], main = 2, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$BIC[[3]], main = 3, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$BIC[[4]], main = 4, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$BIC[[5]], main = 5, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$BIC[[6]], main = 6, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$BIC[[7]], main = 7, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$BIC[[8]], main = 8, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data1$BIC[[9]], main = 9, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#barA Data 1
par(mfrow=c(3,3))
plot(x, barA_data1$BIC[[1]], main = 1, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$BIC[[2]], main = 2, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$BIC[[3]], main = 3, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$BIC[[4]], main = 4, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$BIC[[5]], main = 5, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$BIC[[6]], main = 6, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$BIC[[7]], main = 7, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$BIC[[8]], main = 8, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data1$BIC[[9]], main = 9, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#barB Data 1
par(mfrow=c(3,3))
plot(x, barB_data1$BIC[[1]], main = 1, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$BIC[[2]], main = 2, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$BIC[[3]], main = 3, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$BIC[[4]], main = 4, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$BIC[[5]], main = 5, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$BIC[[6]], main = 6, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$BIC[[7]], main = 7, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$BIC[[8]], main = 8, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data1$BIC[[9]], main = 9, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))


y.low = 330
y.high = 470
#bar0 Data 10
par(mfrow=c(3,3))
plot(x, bar0_data10$BIC[[1]], main = 1, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$BIC[[2]], main = 2, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$BIC[[3]], main = 3, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$BIC[[4]], main = 4, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$BIC[[5]], main = 5, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$BIC[[6]], main = 6, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$BIC[[7]], main = 7, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$BIC[[8]], main = 8, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, bar0_data10$BIC[[9]], main = 9, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#barA Data 10
par(mfrow=c(3,3))
plot(x, barA_data10$BIC[[1]], main = 1, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$BIC[[2]], main = 2, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$BIC[[3]], main = 3, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$BIC[[4]], main = 4, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$BIC[[5]], main = 5, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$BIC[[6]], main = 6, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$BIC[[7]], main = 7, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$BIC[[8]], main = 8, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barA_data10$BIC[[9]], main = 9, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))

#barB Data 10
par(mfrow=c(3,3))
plot(x, barB_data10$BIC[[1]], main = 1, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$BIC[[2]], main = 2, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$BIC[[3]], main = 3, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$BIC[[4]], main = 4, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$BIC[[5]], main = 5, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$BIC[[6]], main = 6, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$BIC[[7]], main = 7, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$BIC[[8]], main = 8, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
plot(x, barB_data10$BIC[[9]], main = 9, ylab="BIC", xlab="Time", ylim=c(y.low,y.high))
par(mfrow=c(1,1))
