#analysis data obtained from move simulations

bar0_data0a = readRDS("bar0_data0a.RData")
bar0_data0b = readRDS("bar0_data0b.RData")
bar0_data1 = readRDS("bar0_data1.RData")
bar0_data2 = readRDS("bar0_data2.RData")
bar0_data3 = readRDS("bar0_data3.RData")
bar0_data4 = readRDS("bar0_data4.RData")
bar0_data5 = readRDS("bar0_data5.RData")
bar0_data6 = readRDS("bar0_data6.RData")
bar0_data7 = readRDS("bar0_data7.RData")
bar0_data8 = readRDS("bar0_data8.RData")
bar0_data9 = readRDS("bar0_data9.RData")
bar0_data10 = readRDS("bar0_data10.RData")

barA_data0a = readRDS("barA_data0a.RData")
barA_data0b = readRDS("barA_data0b.RData")
barA_data1 = readRDS("barA_data1.RData")
barA_data2 = readRDS("barA_data2.RData")
barA_data3 = readRDS("barA_data3.RData")
barA_data4 = readRDS("barA_data4.RData")
barA_data5 = readRDS("barA_data5.RData")
barA_data6 = readRDS("barA_data6.RData")
barA_data7 = readRDS("barA_data7.RData")
barA_data8 = readRDS("barA_data8.RData")
barA_data9 = readRDS("barA_data9.RData")
barA_data10 = readRDS("barA_data10.RData")

barB_data0a = readRDS("barB_data0a.RData")
barB_data0b = readRDS("barB_data0b.RData")
barB_data1 = readRDS("barB_data1.RData")
barB_data2 = readRDS("barB_data2.RData")
barB_data3 = readRDS("barB_data3.RData")
barB_data4 = readRDS("barB_data4.RData")
barB_data5 = readRDS("barB_data5.RData")
barB_data6 = readRDS("barB_data6.RData")
barB_data7 = readRDS("barB_data7.RData")
barB_data8 = readRDS("barB_data8.RData")
barB_data9 = readRDS("barB_data9.RData")
barB_data10 = readRDS("barB_data10.RData")

x = c(1:2000)
par(mfrow=c(3,3))
plot(x, bar0_data0a$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data0a$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data0a$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data0a$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data0a$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data0a$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data0a$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data0a$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data0a$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data0a$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data1$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data1$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data1$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data1$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data1$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data1$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data1$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data1$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data1$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data1$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data2$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data2$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data2$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data2$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data2$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data2$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data2$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data2$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data2$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data2$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data3$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data3$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data3$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data3$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data3$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data3$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data3$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data3$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data3$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data3$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data4$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data4$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data4$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data4$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data4$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data4$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data4$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data4$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data4$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data4$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data5$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data5$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data5$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data5$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data5$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data5$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data5$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data5$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data5$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data5$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data6$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data6$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data6$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data6$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data6$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data6$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data6$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data6$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data6$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data6$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data7$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data7$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data7$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data7$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data7$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data7$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data7$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data7$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data7$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data7$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data8$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data8$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data8$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data8$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data8$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data8$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data8$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data8$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data8$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data8$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data9$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data9$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data9$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data9$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data9$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data9$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data9$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data9$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data9$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data9$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))

par(mfrow=c(3,3))
plot(x, bar0_data10$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
plot(x, bar0_data10$MSE[2]$`current_result$MSE[, 1]`, main = 2, ylab="MSE", xlab="Time")
plot(x, bar0_data10$MSE[3]$`current_result$MSE[, 1]`, main = 3, ylab="MSE", xlab="Time")
plot(x, bar0_data10$MSE[4]$`current_result$MSE[, 1]`, main = 4, ylab="MSE", xlab="Time")
plot(x, bar0_data10$MSE[5]$`current_result$MSE[, 1]`, main = 5, ylab="MSE", xlab="Time")
plot(x, bar0_data10$MSE[6]$`current_result$MSE[, 1]`, main = 6, ylab="MSE", xlab="Time")
plot(x, bar0_data10$MSE[7]$`current_result$MSE[, 1]`, main = 7, ylab="MSE", xlab="Time")
plot(x, bar0_data10$MSE[8]$`current_result$MSE[, 1]`, main = 8, ylab="MSE", xlab="Time")
plot(x, bar0_data10$MSE[9]$`current_result$MSE[, 1]`, main = 9, ylab="MSE", xlab="Time")
#plot(x, bar0_data10$MSE[10]$`current_result$MSE[, 1]`, main = 10, ylab="MSE", xlab="Time")
par(mfrow=c(1,1))


fit.1 = lm(bar0_data0a$MSE[1]$`current_result$MSE[, 1]`~x)
plot(x, bar0_data1$MSE[1]$`current_result$MSE[, 1]`, main = 1, ylab="MSE", xlab="Time")
abline(lm(bar0_data0a$MSE[1]$`current_result$MSE[, 1]`~(x)^2) ,col="red",lwd=2)
lines(lowess(x,bar0_data0a$MSE[1]$`current_result$MSE[, 1]`), col="blue",lwd=2)
lines(smooth.spline(x,bar0_data0a$MSE[1]$`current_result$MSE[, 1]`), col="green", lwd=2)
smoothed25 <- predict(loess(bar0_data0a$MSE[1]$`current_result$MSE[, 1]`~x , data=bar0_data0a, span=0.25)) 
lines(smoothed25, x=x, col="orange", lwd=3)
